import json
import os
import sqlite3
import stat
import unittest
from pathlib import Path
from unittest import mock

from nju_connect import exporters, xray
from tests.test_policy_and_exports import ExportFixture

# the fields of v2rayN's RulesItem (ServiceLib/Models/Entities/RulesItem.cs)
V2RAYN_FIELDS = {"id", "type", "port", "network", "inboundtag", "outboundtag", "ip", "domain",
                 "protocol", "process", "enabled", "remarks", "ruletype"}

USER_CONFIG = """{
  // a hand-written config: comments and "// inside strings" must survive parsing
  "log": {"loglevel": "warning", "note": "http://example.com/*x*/"},
  "inbounds": [{"tag": "socks-in", "protocol": "socks", "port": 10808}],
  "outbounds": [
    {"tag": "proxy", "protocol": "vless", "settings": {}},   /* the default outbound */
    {"tag": "block", "protocol": "blackhole"}
  ],
  "routing": {"domainStrategy": "AsIs", "rules": [
    {"type": "field", "domain": ["geosite:cn"], "outboundTag": "block"}
  ]}
}
"""


def without_comments(text):
    return json.loads(xray.strip_comments(text))


class V2raynTest(ExportFixture):
    def make_db(self, rules, active=True):
        folder = self.tmp / "v2rayN"
        (folder / "guiConfigs").mkdir(parents=True)
        conn = sqlite3.connect(str(folder / "guiConfigs/guiNDB.db"))
        conn.execute('CREATE TABLE "RoutingItem" ("Id" varchar primary key not null, "Remarks" varchar, '
                     '"RuleSet" varchar, "Sort" integer, "IsActive" integer)')
        conn.execute("INSERT INTO RoutingItem VALUES ('1', 'Other', '[]', 0, 0)")
        conn.execute("INSERT INTO RoutingItem VALUES ('2', 'Whitelist', ?, 1, ?)", (json.dumps(rules), int(active)))
        conn.commit()
        conn.close()
        patcher = mock.patch.dict(os.environ, {"NJU_CONNECT_V2RAYN_DIR": str(folder)})
        patcher.start()
        self.addCleanup(patcher.stop)

    def test_without_v2rayn_only_our_rules(self):
        with mock.patch.object(xray, "v2rayn_dirs", return_value=[]):
            text = self.render("v2rayn")
        self.assertTrue(text.startswith("// Generated by nju-connect"))
        self.assertIn("import with Yes (append)", text)
        rules = without_comments(text)
        self.assertIsInstance(rules, list)   # v2rayN imports a JSON list, not an Xray config
        self.assertEqual(rules[0], {"remarks": "nju-connect: VPN server direct", "domain": ["full:vpn.nju.edu.cn"],
                                    "outboundTag": "direct"})
        self.assertEqual(rules[1]["ip"], ["219.219.118.25/32"])
        self.assertIn({"remarks": "nju-connect: NJU domains, port 80,443", "domain": ["full:lib.nju.edu.cn"],
                       "outboundTag": "NJUConnect", "port": "80,443"}, rules)
        self.assertIn({"remarks": "nju-connect: other nju.edu.cn hosts (resolved by zju-connect)",
                       "domain": ["domain:nju.edu.cn"], "outboundTag": "NJUConnect"}, rules)
        for rule in rules:
            self.assertTrue(rule["remarks"].startswith(xray.REMARK))
            self.assertLessEqual({k.lower() for k in rule}, V2RAYN_FIELDS)

    def test_active_routing_follows_our_rules(self):
        theirs = [{"Id": "9", "OutboundTag": "block", "Domain": ["geosite:category-ads-all"], "Enabled": True,
                   "Remarks": "ads"},
                  {"Id": "8", "OutboundTag": "NJUConnect", "Ip": ["1.1.1.1"], "Enabled": True,
                   "Remarks": "nju-connect: old rule"},
                  {"Id": "7", "OutboundTag": "direct", "Ip": ["geoip:cn"], "Enabled": False, "Remarks": "cn"}]
        self.make_db(theirs)
        text = self.render("v2rayn")
        self.assertIn('active routing "Whitelist"', text)
        rules = without_comments(text)
        ours = [r for r in rules if r.get("remarks", "").startswith(xray.REMARK)]
        self.assertEqual(rules[:len(ours)], ours)
        self.assertEqual(rules[len(ours):], [
            {"OutboundTag": "block", "Domain": ["geosite:category-ads-all"], "Enabled": True, "Remarks": "ads"},
            {"OutboundTag": "direct", "Ip": ["geoip:cn"], "Enabled": False, "Remarks": "cn"}])
        # importing the output and exporting again gives the same rules: no duplicates pile up
        conn = sqlite3.connect(str(Path(os.environ["NJU_CONNECT_V2RAYN_DIR"]) / "guiConfigs/guiNDB.db"))
        conn.execute("UPDATE RoutingItem SET RuleSet = ? WHERE Id = '2'", (json.dumps(rules),))
        conn.commit()
        conn.close()
        self.assertEqual(without_comments(self.render("v2rayn")), rules)

    def test_inactive_routing_is_not_used(self):
        self.make_db([{"OutboundTag": "block", "Ip": ["1.1.1.1"]}], active=False)
        self.assertNotIn("1.1.1.1", self.render("v2rayn"))

    def test_share_link_and_steps(self):
        out = self.tmp / "nju-v2rayn.json"
        with mock.patch.object(xray, "v2rayn_dirs", return_value=[]), \
                mock.patch("builtins.print") as p:
            exporters.export("v2rayn", out)
        printed = "\n".join(str(c.args[0]) for c in p.call_args_list)
        self.assertIn("socks://Og@127.0.0.1:2080#NJUConnect", printed)
        self.assertIn("https://github.com/Huaji-tye2007/nju-connect-cli/blob/main/docs/proxy-clients.md#v2rayn",
                      printed)   # installed users have no docs/ folder
        self.assertNotIn("Domain strategy", printed)   # not needed: nju.edu.cn goes to zju-connect
        self.assertEqual(exporters.remembered(), {"v2rayn": str(out.resolve())})


class XrayMergeTest(ExportFixture):
    def setUp(self):
        super().setUp()
        self.conf = self.tmp / "config.json"
        self.conf.write_text(USER_CONFIG)
        os.chmod(self.conf, 0o640)
        # never run a real xray or touch a real service
        for name, value in (("xray_binary", None), ("xray_units", [])):
            patcher = mock.patch.object(xray, name, return_value=value)
            patcher.start()
            self.addCleanup(patcher.stop)

    def install(self):
        with mock.patch("builtins.print"):
            exporters.export("xray", self.conf, install=True)

    def test_merge(self):
        self.install()
        data = json.loads(self.conf.read_text())
        self.assertEqual([o["tag"] for o in data["outbounds"]], ["proxy", "block", "direct", "NJUConnect"])
        self.assertEqual(data["outbounds"][-1]["settings"]["servers"], [{"address": "127.0.0.1", "port": 2080}])
        rules = data["routing"]["rules"]
        self.assertEqual(rules[0], {"type": "field", "domain": ["full:vpn.nju.edu.cn"], "outboundTag": "direct",
                                    "ruleTag": "nju-connect"})
        self.assertEqual(rules[-1], {"type": "field", "domain": ["geosite:cn"], "outboundTag": "block"})
        self.assertEqual(data["routing"]["domainStrategy"], "AsIs")   # the user's own setting is kept
        self.assertIn({"type": "field", "domain": ["domain:nju.edu.cn"], "outboundTag": "NJUConnect",
                       "ruleTag": "nju-connect"}, rules)
        self.assertEqual(data["log"]["note"], "http://example.com/*x*/")
        self.assertEqual(stat.S_IMODE(self.conf.stat().st_mode), 0o640)
        self.assertEqual(len(list(self.tmp.glob("config.json.bak-*"))), 1)
        self.assertEqual(exporters.remembered(), {"xray": exporters.MERGE + str(self.conf.resolve())})

    def test_merging_again_is_idempotent(self):
        self.install()
        first = self.conf.read_text()
        self.install()
        self.assertEqual(self.conf.read_text(), first)
        self.assertEqual(len(list(self.tmp.glob("config.json.bak-*"))), 1)   # backed up only once

    def test_refresh_replaces_our_rules_and_restarts(self):
        self.install()
        count = self.conf.read_text().count('"ruleTag": "nju-connect"')
        data = json.loads(self.conf.read_text())
        data["routing"]["rules"][0]["domain"] = ["full:stale.example.com"]
        self.conf.write_text(json.dumps(data))
        with mock.patch.object(xray, "restart_xray", return_value=(True, "Restarted xray.service")) as restart:
            self.assertEqual(exporters.refresh_exports(quiet=True), 1)
        restart.assert_called_once_with()
        text = self.conf.read_text()
        self.assertNotIn("stale.example.com", text)
        self.assertEqual(text.count('"ruleTag": "nju-connect"'), count)

    def test_rejected_config_is_left_unchanged(self):
        with mock.patch.object(xray, "check_config", side_effect=RuntimeError("xray rejected it")), \
                mock.patch("builtins.print"), self.assertRaises(SystemExit):
            exporters.export("xray", self.conf, install=True)
        self.assertEqual(self.conf.read_text(), USER_CONFIG)

    def test_refuses_v2rayn_generated_config(self):
        (self.tmp / "guiConfigs").mkdir()
        (self.tmp / "binConfigs").mkdir()
        conf = self.tmp / "binConfigs/config.json"
        conf.write_text(USER_CONFIG)
        with self.assertRaisesRegex(RuntimeError, "export v2rayn"):
            xray.merge_file(conf, [], {}, {"export": {"proxy_name": "NJUConnect"}})

    def test_not_an_xray_config(self):
        self.conf.write_text('{"inbounds": []}')
        with self.assertRaisesRegex(RuntimeError, "no outbounds"):
            xray.merge_file(self.conf, [], {}, {"export": {"proxy_name": "NJUConnect"}})

    def test_restart_only_user_services(self):
        units = [("user", "xray.service"), ("system", "xray@main.service")]
        env = {k: v for k, v in os.environ.items() if k != "NJU_CONNECT_CONFIG_DIR"}
        with mock.patch.dict(os.environ, env, clear=True), \
                mock.patch.object(xray, "xray_units", return_value=units), \
                mock.patch.object(xray.subprocess, "run") as run:
            self.assertEqual(xray.restart_xray(), (True, "Restarted xray.service"))
            run.assert_called_once_with(["systemctl", "--user", "restart", "xray.service"], timeout=60)
            run.reset_mock()
            restarted, message = xray.restart_xray(confirm=lambda prompt: False)
        run.assert_not_called()
        self.assertFalse(restarted)
        self.assertIn("sudo systemctl restart xray@main.service", message)

    def test_sandbox_never_restarts(self):
        with mock.patch.object(xray.subprocess, "run") as run:
            self.assertFalse(xray.restart_xray()[0])
        run.assert_not_called()


class StripCommentsTest(unittest.TestCase):
    def test_strip_comments(self):
        text = '{"a": "x // y", # hash comment\n "b": /* c */ "\\"/*"}'
        self.assertEqual(json.loads(xray.strip_comments(text)), {"a": "x // y", "b": '"/*'})
