import configparser
import io
import json
import os
import shutil
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest import mock

from nju_connect import cli, clients, config, exporters, paths, singbox, xray
from tests.test_install import SING_BOX_CONFIG
from tests.test_policy_and_exports import ExportFixture, remembered_dict


def run(*argv):
    """(exit code, stdout + stderr) of `nju-connect ARGV`, without colors."""
    out = io.StringIO()
    env = {k: v for k, v in os.environ.items() if k not in ("FORCE_COLOR", "PYTHON_COLORS")}
    env.update(NO_COLOR="1", COLUMNS="100")
    with mock.patch.dict(os.environ, env, clear=True), redirect_stdout(out), redirect_stderr(out):
        try:
            args = cli.build_parser().parse_args(list(argv))
            args.func(args)
            code = 0
        except SystemExit as e:
            code = e.code or 0
    return code, out.getvalue()


class HelpTest(ExportFixture):
    def test_each_format_has_its_own_help(self):
        code, text = run("export", "xray", "-h")
        self.assertEqual(code, 0)
        self.assertIn("usage: nju-connect export xray", text)
        self.assertIn("restarts Xray", text)
        self.assertIn("--install", text)
        self.assertNotIn("mihomo-script", text)   # not the whole export help
        _, text = run("export", "pac", "-h")
        self.assertNotIn("--install", text)
        self.assertIn("file:///home/<you>/nju.pac", text)

    def test_overview(self):
        _, text = run("export", "-h")
        for name in exporters.FORMATS:
            self.assertIn(name, text)
        self.assertIn("nju-connect export FORMAT -h", text)

    def test_inline_is_gone(self):
        code, text = run("export", "clash-verge", "--inline", "-o", str(self.tmp / "x.js"))
        self.assertEqual(code, 2)
        self.assertIn("mihomo-script", text)

    def test_clash_verge_needs_install(self):
        code, text = run("export", "clash-verge")
        self.assertEqual(code, 1)
        self.assertIn("mihomo-script", text)

    def test_list_and_forget_need_no_format(self):
        self.assertIn("No remembered exports", run("export", "--list")[1])
        self.assertEqual(run("export")[0], 1)   # a format, --list or --forget


class SeveralExportsTest(ExportFixture):
    def export(self, *argv):
        code, text = run("export", *argv)
        self.assertEqual(code, 0, text)
        return text

    def test_several_per_format(self):
        a, b = self.tmp / "a.js", self.tmp / "b.js"
        self.export("mihomo-script", "-o", str(a))
        self.export("mihomo-script", "-o", str(b))
        self.export("mihomo-script", "-o", str(a))   # the same again: no new entry
        self.export("pac", "-o", str(self.tmp / "nju.pac"))
        self.assertEqual(remembered_dict(), {"mihomo-script": str(a), "mihomo-script@2": str(b),
                                             "pac": str(self.tmp / "nju.pac")})
        for path in (a, b):
            path.write_text("// Generated by nju-connect (stale)\n")
        self.assertEqual(exporters.refresh_exports(quiet=True), 2)   # both kept up to date
        self.assertIn("function main(config)", b.read_text())

    def test_forget(self):
        a, b = self.tmp / "a.js", self.tmp / "b.js"
        for path in (a, b):
            self.export("mihomo-script", "-o", str(path))
        self.export("pac", "-o", str(self.tmp / "nju.pac"))
        self.assertIn("mihomo-script@2", self.export("--forget", "mihomo-script@2"))   # a name
        self.export("--forget", str(self.tmp / "nju.pac"))                             # a path
        self.assertEqual(remembered_dict(), {"mihomo-script": str(a)})
        self.export("mihomo-script", "-o", str(b))
        self.export("--forget", "mihomo-script")                                       # a format: all
        self.assertEqual(remembered_dict(), {})
        self.assertEqual(run("export", "--forget", "pac")[0], 1)

    def test_list_shows_every_kept_file(self):
        (paths.VERGE_DIR / "profiles").mkdir(parents=True)
        self.addCleanup(shutil.rmtree, paths.VERGE_DIR)
        with mock.patch.object(exporters, "apply_verge_script"):
            self.export("clash-verge", "--install")
        self.export("v2rayn", "-o", str(self.tmp / "nju-v2rayn.json"))
        (paths.VERGE_DIR / "proxies/nju-connect.yaml").unlink()
        _, text = run("export", "--list")
        self.assertIn("clash-verge      installed into Clash Verge Rev", text)
        for name in ("profiles/Script.js", "ruleset/nju-vpn.yaml", "ruleset/nju-direct.yaml"):
            self.assertRegex(text, rf"{name}\s+updated 0\.0h ago")
        self.assertRegex(text, r"proxies/nju-connect\.yaml\s+missing")
        self.assertIn("import it again after it changes", text)   # v2rayn


class MigrationTest(ExportFixture):
    def test_inline_entries(self):
        old = configparser.ConfigParser()
        old.read_dict({"exports": {"clash-verge": "inline:/home/u/nju-flclash.js",
                                   "clash-config": "inline:/home/u/party.yaml",
                                   "sing-box-config": "inline:/home/u/sb.json",
                                   "mihomo-script": "/home/u/other.js"}})
        with open(paths.SETTINGS_FILE, "w") as f:
            old.write(f)
        self.assertEqual(dict(config.load_settings()["exports"]), {
            "clash-config": "/home/u/party.yaml", "sing-box-config": "/home/u/sb.json",
            "mihomo-script": "/home/u/other.js", "mihomo-script@2": "/home/u/nju-flclash.js"})


class UnwritableInstallTest(ExportFixture):
    def setUp(self):
        super().setUp()
        if os.getuid() == 0:
            self.skipTest("root can write anywhere")
        self.conf = self.tmp / "config.json"
        self.conf.write_text(SING_BOX_CONFIG)
        os.chmod(self.conf, 0o444)
        os.chmod(self.tmp, 0o555)
        self.addCleanup(os.chmod, self.tmp, 0o755)
        self.addCleanup(shutil.rmtree, paths.SING_BOX_RULE_SETS, True)
        if exporters.SNIPPETS.exists():
            exporters.SNIPPETS.unlink()
        patcher = mock.patch.object(clients, "running", return_value=[])
        patcher.start()
        self.addCleanup(patcher.stop)

    def test_sing_box_rule_sets_in_our_folder_and_steps(self):
        code, text = run("export", "sing-box-config", "--install", "-o", str(self.conf))
        self.assertEqual(code, 0, text)
        self.assertEqual(self.conf.read_text(), SING_BOX_CONFIG)   # left alone
        for name in singbox.RULE_SETS:
            self.assertTrue((paths.SING_BOX_RULE_SETS / f"{name}.json").exists())
        self.assertIn("is not writable by you", text)
        self.assertIn("① Under outbounds:", text)
        self.assertIn("③ At the TOP of route.rules:", text)
        self.assertIn(f'"path": "{paths.SING_BOX_RULE_SETS / "nju-vpn.json"}"', text)
        self.assertIn('{"rule_set": "nju-direct", "outbound": "direct-out"},', text)   # the config's direct
        self.assertEqual(remembered_dict(), {"sing-box-config": exporters.INSTALL + str(self.conf)})
        _, listing = run("export", "--list")
        self.assertIn("(merged by hand once)", listing)
        # policy changes: the rule sets follow, nothing to merge
        (paths.SING_BOX_RULE_SETS / "nju-vpn.json").write_text("{}")
        with mock.patch.object(exporters, "notify") as notify:
            exporters.refresh_exports(quiet=True)
            notify.assert_not_called()
            self.assertIn("ip_cidr", (paths.SING_BOX_RULE_SETS / "nju-vpn.json").read_text())
            config.set_options({"export.proxy_name": "NJU2"})   # the merged part changes
            self.addCleanup(config.set_options, {"export.proxy_name": "NJUConnect"})
            exporters.refresh_exports(quiet=True)
        self.assertTrue(any("merge it again" in c.args[0] for c in notify.call_args_list))

    def test_xray_prints_and_is_not_kept(self):
        self.conf.chmod(0o644)
        os.chmod(self.tmp, 0o755)
        self.conf.write_text('{"outbounds": [{"tag": "proxy", "protocol": "vless"}]}')
        os.chmod(self.conf, 0o444)
        os.chmod(self.tmp, 0o555)
        with mock.patch.object(xray, "xray_binary", return_value=None):
            code, text = run("export", "xray", "--install", "-o", str(self.conf))
        self.assertEqual(code, 0, text)
        self.assertIn("② At the TOP of routing.rules:", text)
        self.assertIn('"ruleTag": "nju-connect"', text)
        self.assertIn("Not kept up to date", text)
        self.assertEqual(remembered_dict(), {})   # nothing the service could keep up to date


if __name__ == "__main__":
    unittest.main()
