"""Clash Verge Rev global script / mihomo snippet that routes NJU resources via zju-connect."""

import json
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

from . import VERSION, paths
from .config import DEFAULT_SERVER, socks_address
from .ruleset import ruleset_path
from .util import die, write_atomic

MARKER = "Generated by nju-connect"


def ruleset_payload(settings):
    output = ruleset_path(settings)
    if not output.exists():
        die(f"{output} not found; run `nju-connect ruleset` first")
    return [line[5:-1] for line in output.read_text().splitlines() if line.startswith("  - '")]


def clash_parts(config, settings, inline=False):
    host, port = socks_address(config)
    c = settings["clash"]
    proxy = {"name": c["proxy_name"], "type": "socks5", "server": host, "port": port, "udp": True}
    group = {"name": c["group_name"], "type": c["group_type"], "proxies": [c["proxy_name"], "DIRECT"]}
    if c["group_type"] in ("fallback", "url-test"):
        group.update({"url": c["health_url"], "interval": int(c["health_interval"])})
    provider_path = settings["ruleset"]["provider_path"] or paths.detect_clash()[1]
    if not inline and os.path.isabs(provider_path):
        # mihomo only reads provider files inside its own home directory
        print("nju-connect: no Clash Verge Rev/mihomo directory detected, embedding the rules "
              "inline (set ruleset.output/ruleset.provider_path to use a file instead)", file=sys.stderr)
        inline = True
    if inline:
        provider = {"type": "inline", "behavior": "classical", "payload": ruleset_payload(settings)}
    else:
        provider = {"type": "file", "behavior": "classical", "format": "yaml", "path": provider_path}
    rules = [
        # keep zju-connect's own connection to the VPN server out of the proxy
        f"DOMAIN,{config.get('server_address', DEFAULT_SERVER)},DIRECT",
        f"RULE-SET,nju-vpn,{c['group_name']}",
    ]
    return proxy, group, provider, rules


def _js(value):
    return json.dumps(value, ensure_ascii=False)


def clash_js(config, settings, inline=False):
    proxy, group, provider, rules = clash_parts(config, settings, inline)
    return f"""// {MARKER} {VERSION}; regenerate with `nju-connect clash-script --install`
// Proxies NJU resources through zju-connect ({proxy['server']}:{proxy['port']}); the {group['type']}
// group falls back to DIRECT while zju-connect is not running (e.g. on campus).
function main(config) {{
  const proxy = {_js(proxy)};
  const group = {_js(group)};
  const provider = {_js(provider)};
  const rules = {_js(rules)};

  config.proxies = (config.proxies || []).filter((p) => p.name !== proxy.name);
  config.proxies.push(proxy);
  config["proxy-groups"] = (config["proxy-groups"] || []).filter((g) => g.name !== group.name);
  config["proxy-groups"].push(group);
  config["rule-providers"] = config["rule-providers"] || {{}};
  config["rule-providers"]["nju-vpn"] = provider;
  config.rules = rules.concat(config.rules || []);

  console.log("nju-connect: injected " + proxy.name + ", group " + group.name + " and ruleset nju-vpn");
  return config;
}}
"""


def clash_yaml(config, settings, inline=False):
    proxy, group, provider, rules = clash_parts(config, settings, inline)
    lines = [f"# {MARKER}; merge into your mihomo config.",
             "proxies:", f"  - {_js(proxy)}",
             "proxy-groups:", f"  - {_js(group)}",
             "rule-providers:", f"  nju-vpn: {_js(provider)}",
             "rules:  # put these above your other rules"]
    lines += [f"  - {rule}" for rule in rules]
    return "\n".join(lines) + "\n"


def install_clash_script(config, settings, target=None, inline=False):
    target = Path(target or settings["clash"]["script"] or "")
    if not str(target) or str(target) == ".":
        die("no Clash Verge Rev global script found; use --output FILE or --format yaml")
    content = clash_js(config, settings, inline)
    if target.exists():
        if target.read_text() == content:
            print(f"{target} is already up to date")
            return
        backup = target.with_name(f"{target.name}.bak-{datetime.now():%Y%m%d-%H%M%S}")
        shutil.copy2(target, backup)
        print(f"Backed up {target} -> {backup}")
    write_atomic(target, content, 0o644)
    print(f"Wrote {target}; reload your profile in Clash Verge to apply it")


def refresh_installed_script(config, settings):
    """Regenerate the Clash Verge script if nju-connect generated it; True if it did."""
    target = Path(settings["clash"]["script"] or "")
    if not str(target) or str(target) == "." or not target.exists() or MARKER not in target.read_text():
        return False
    install_clash_script(config, settings, target)
    return True
